version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
    command: gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 app:app

volumes:
  app-data: